site_name: Fiction Ideas
site_url: https://www.fictionideas.com/
site_description: Product Ideas from Fiction
site_author: Ashvin

theme:
  name: material
  icon:
    logo: material/view-grid-plus
  favicon: assets/view-grid-plus-outline-dark.png
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

copyright: Copyright &copy; 2023-2024 Ashvin Parameswaran

extra:
  social:
    - icon: material/alpha-k-circle-outline
      link: https://ashvin.au

nav:
  - Home: README.md
  - How It Works: howitworks.md
  - Ideas:
      - GlimmerCraft: 1.md
      - ChronoCuisine: 2.md
      - WhimsiQuill: 3.md
      - LustraGem: 4.md
      - Glintroam Odyssey Tours: 5.md
      - SteamCraft Innovations: 6.md
      - Mystique & Masquerade: 7.md
      - Galactic Questers: 8.md
      - Cosmos Canvas: 9.md
      - AquaTents ğŸµ: 10.md
      - Haiku Harmonics: 11.md
      - Whispering Gardens ğŸ“½ï¸: 12.md
      - Celestial Harmonics: 13.md
      - Gravitational Harmony Homes: 14.md
      - CafÃ©-Oruga Comms: 15.md
      - MoodHues Chapeau: 16.md
      - Fyrestoke Hearth & Home: 17.md
      - Waxen Calm ğŸµ: 18.md
      - Nether's Bane: 19.md
      - Sleight of Hand Academy: 20.md
      - Rattle's Raid Rides ğŸµğŸ“½ï¸: 21.md
      - SwiftTrade ğŸ’²: 22.md
